name: budgethero
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  hive_flutter: ^1.1.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  multi_select_flutter: ^4.1.3
  uuid: ^4.5.1
  dartz: ^0.10.1
  path_provider: ^2.1.5
  equatable: ^2.0.7
  image_picker: ^1.1.2
  awesome_dio_interceptor: ^1.3.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.4
  permission_handler: ^12.0.0+1
  json_serializable: ^6.9.0
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/logo/logo.png

  fonts:
    - family: Jaro
      fonts:
        - asset: assets/fonts/Jaro-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
